import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Cookie Policy",
};

interface DefinitionItem {
  term: string;
  definition: string;
}

interface PolicySection {
  id: string;
  title: string;
  content: React.ReactNode;
}

export default function CookiePolicy() {
  const lastUpdated = "2026-06-13";

  const keyTerms: DefinitionItem[] = [
    { term: "Cookie", definition: "Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information." },
    { term: "Company", definition: "When this policy mentions “Company,” “we,” “us,” or “our,” it refers to TaQtiQ, that is responsible for your information under this Cookie Policy." },
    { term: "Device", definition: "Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit TaQtiQ and use the services." },
    { term: "Personal Data", definition: "Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person." },
    { term: "Service", definition: "Refers to the service provided by TaQtiQ as described in the relative terms (if available) and on this platform." },
    { term: "Third-party service", definition: "Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you." },
    { term: "Website", definition: "TaQtiQ's site, which can be accessed via this URL: https://www.taqtiq.tech/" },
  ];

  const browserLinks = [
    { name: "Google Chrome", url: "https://support.google.com/chrome" },
    { name: "Internet Explorer", url: "https://support.microsoft.com" },
    { name: "Mozilla Firefox", url: "https://support.mozilla.org" },
    { name: "Safari (Desktop)", url: "https://support.apple.com" },
    { name: "Safari (Mobile)", url: "https://support.apple.com" },
    { name: "Android Browser", url: "https://support.google.com/android" },
    { name: "Opera", url: "https://blogs.opera.com" },
    { name: "Opera Mobile", url: "https://www.opera.com/mobile" },
  ];

  const sections: PolicySection[] = [
    {
      id: "definitions",
      title: "Definitions and key terms",
      content: (
        <div className="space-y-6">
          <p className="text-muted-foreground">
            To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, they are strictly defined as:
          </p>
          <ul className="space-y-4 border-l-2 border-border pl-4">
            {keyTerms.map((item, idx) => (
              <li key={idx} className="text-base leading-relaxed">
                <strong className="text-foreground font-semibold">{item.term}:</strong>{" "}
                <span className="text-muted-foreground">{item.definition}</span>
              </li>
            ))}
          </ul>
          <p className="pt-2">
            This Cookie Policy was created with{" "}
            <a 
              href="https://termify.io" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="text-primary font-medium underline underline-offset-4 hover:text-primary/80 transition-colors"
            >
              Termify
            </a>
            .
          </p>
        </div>
      ),
    },
    {
      id: "introduction",
      title: "Introduction",
      content: (
        <p>
          This Cookie Policy explains how TaQtiQ and its affiliates (collectively "TaQtiQ", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website, including without limitation https://www.taqtiq.tech/ and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.
        </p>
      ),
    },
    {
      id: "what-is-cookie",
      title: "What is a cookie?",
      content: (
        <p>
          A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.
        </p>
      ),
    },
    {
      id: "why-cookies",
      title: "Why do we use cookies?",
      content: (
        <div className="space-y-4">
          <p>We use first party and/or third party cookies on our website for various purposes such as:</p>
          <ul className="list-disc pl-5 space-y-2 text-muted-foreground text-base">
            <li>To facilitate the operation and functionality of our website;</li>
            <li>To improve your experience of our website and make navigating around them quicker and easier;</li>
            <li>To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;</li>
            <li>To analyze how our website is used and how best we can customize it;</li>
            <li>To identify future prospects and personalize marketing and sales interactions with it;</li>
            <li>To facilitate the tailoring of online advertising to your interests.</li>
            <li>You: a person or entity that is registered with TaQtiQ to use the Services.</li>
          </ul>
        </div>
      ),
    },
    {
      id: "cookie-types",
      title: "What type of cookies does TaQtiQ use?",
      content: (
        <div className="space-y-6">
          <p>
            Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”.
          </p>
          <p>
            Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.
          </p>
          <p>We use the following types of cookies in our website:</p>

          <div className="space-y-6 border-t border-border/40 pt-6 mt-6">
            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Essential Cookies</h3>
              <p>We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Performance and Functionality Cookies</h3>
              <p>These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Marketing Cookies</h3>
              <p>These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Analytics and Customization Cookies</h3>
              <p>These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our website for you.</p>
              <p className="text-sm bg-muted/40 p-3 rounded-lg border border-border/40">
                We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at:{" "}
                <a href="https://www.google.com/policies/privacy/partners/" target="_blank" rel="noopener noreferrer" className="text-primary underline">
                  Google Privacy Policy
                </a>
                . You can opt-out of analytics by visiting:{" "}
                <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-primary underline">
                  Google Analytics Opt-out Browser Add-on
                </a>
                .
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Social Media Cookies</h3>
              <p>These cookies are used when you share information using a social media sharing button or “like” button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-medium text-foreground">Third Party Cookies</h3>
              <p>Some cookies that have been set on our website are not set on a first party basis by TaQtiQ. The Websites can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.</p>
            </div>
          </div>
        </div>
      ),
    },
    {
      id: "manage-cookies",
      title: "How you can manage cookies?",
      content: (
        <div className="space-y-4">
          <p>
            Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.
          </p>
          <p>Please see below for more information from standard browser manufacturers:</p>
          <ul className="grid grid-cols-2 gap-2 sm:grid-cols-4 text-base text-muted-foreground">
            {browserLinks.map((browser, idx) => (
              <li key={idx}>
                <a 
                  href={browser.url} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-primary hover:underline underline-offset-2 font-medium"
                >
                  {browser.name}
                </a>
              </li>
            ))}
          </ul>
        </div>
      ),
    },
    {
      id: "disabling-cookies",
      title: "Blocking and disabling cookies and similar technologies",
      content: (
        <p>
          Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
        </p>
      ),
    },
    {
      id: "changes",
      title: "Changes To Our Cookie Policy",
      content: (
        <p>
          We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.
        </p>
      ),
    },
    {
      id: "consent",
      title: "Your Consent",
      content: (
        <p>
          By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.
        </p>
      ),
    },
    {
      id: "contact",
      title: "Contact Us",
      content: (
        <p className="text-muted-foreground">
          Don't hesitate to contact us if you have any questions regarding our Cookie Policy at <span className="font-medium text-foreground">support@taqtiq.tech</span>.
        </p>
      ),
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <header className="border-b border-border pb-8 mb-12">
          <h1 className="text-4xl font-bold tracking-tight mb-3 sm:text-5xl">
            Cookie Policy
          </h1>
          <p className="text-sm text-muted-foreground">
            Updated at: <time dateTime={lastUpdated}>{lastUpdated}</time>
          </p>
        </header>

        <div className="space-y-14">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="scroll-mt-20 border-t border-border/40 pt-8 first:border-t-0 first:pt-0">
              <h2 className="text-xl font-semibold tracking-tight text-foreground mb-4">
                {section.title}
              </h2>
              <div className="text-base leading-relaxed text-muted-foreground space-y-4">
                {section.content}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}