/* Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/grid-cube.glb --typescript 
*/
'use client'

import { useGLTF, OrbitControls, Stage } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/grid-cube.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/grid-cube.glb')

export default function GridCubeScene() {
  return (
    <div className="w-full h-full min-h-[400px]">
      <Canvas camera={{ position: [0, 0, 14], fov: 45 }}>
        <ambientLight intensity={0.7} />
        <directionalLight position={[5, 5, 5]} intensity={1.5} />
        
        <Stage intensity={0.5} environment="city" adjustCamera={false}>
          <Model />
        </Stage>
        
        <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={0.6} />
      </Canvas>
    </div>
  )
}